version: "3.5"

services:
  # flask_api:
  #   container_name: flask_api
  #   build: ./app
  #   volumes:
  #     - "./app/:/app"
  #   ports:
  #     - "5000:5000"

  flask_resful_docker:
    container_name: flask_resful_docker
    build: ./flask-restful-docker
    volumes:
      - "./flask-restful-docker/:/app"
    ports:
      - "5000:5000"
    environment:
      JWT_SECRET: ${JWT_SECRET:-some_secret_jwt_key}

  flask_log_monitor:
    container_name: flask_log_monitor
    restart: unless-stopped
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
