version: "3.5"

services:
  flask_api:
    container_name: flask_api
    build: ./app
    volumes:
      - "./app/:/app"
    ports:
      - "5000:5000"

  log_monitor:
    container_name: log_monitor
    restart: unless-stopped
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
